### PR TITLE
Numpy_Assignment_Ainembabazi_Moses_2022/HDO7/2039U.

### PR DESCRIPTION
**Pull request by mozey256**

### CODE REVIEW

**Comment by atwine** [comment]
Your file is not in the folder, please verify

**Comment by mozey256** [comment]
I have tried to put it in the folder but an not seeing it change here

**Comment by atwine** [comment]
> I have tried to put it in the folder but an not seeing it change here

You can't push to my repo without me accepting it.
I will show us how to follow through with this tomorrow.

**Comment by mozey256** [comment]
Ok thank you very much

**Comment by mozey256** [comment]
I have renamed my file hoping it fits what is required.
thank you

**Pull request closed without merging**
